name: gd_hyperopt
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - optuna>=3.0.0
  - pyyaml>=6.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - pip
  - pip:
    # Add any pip-only packages here if needed
    # - some-pip-only-package
