name: ssm_generalize
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - scikit-learn
  - gputil=1.4.0
  - matplotlib=3.10.3
  - numpy
  - pandas=2.3.1
  - python-constraint=1.4.0
  - scheduler=0.8.8
  - scipy=1.16.0
  - seaborn=0.13.2
  - pytorch=2.7.1
  - tqdm=4.66.5
  - psutil=3.3.11
